name: Sync to Gitee
on:
  push:
    branches:
      - master
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@v1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
        with:
          source-repo: 'git@github.com:caigq99/rust-practive.git'
          destination-repo: 'git@gitee.com:caigq99/rust-practive.git'
